apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: infra-template
  title: .NET Infrastructure Add-on
  description: Adiciona AppDatabaseContext.cs ao projeto existente
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Informações do Projeto
      required:
        - name
      properties:
        name:
          title: Nome do Projeto
          type: string
          description: O nome do projeto (deve coincidir com o projeto base)

  steps:
    - id: fetch-base
      name: Buscando Skeleton de Infraestrutura
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: publish-pr
      name: Abrir Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=MDev-Debug&repo=${{ parameters.name }}
        branchName: 'add-infrastructure-context'
        title: 'Adicionando AppDatabaseContext'
        description: 'Este PR adiciona o AppDatabaseContext.cs na camada de infraestrutura.'

  output:
    links:
      - title: Pull Request
        url: ${{ steps['publish-pr'].output.remoteUrl }}