apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: infra-sqlserver
  title: Infraestrutura SQL Server
  description: Adiciona DbContext e SQL Server a uma API .NET existente.
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Configuração Básica
      required:
        - projectName
        - dbContextName
      properties:
        projectName:
          title: Nome do Projeto .NET
          type: string
        dbContextName:
          title: Nome do DbContext
          type: string

  steps:
    - id: fetch-repo
      name: Clonar repositório
      action: fetch:plain
      input:
        repoUrl: github.com?owner=MDev-Debug&repo=${{ parameters.projectName }}
        targetPath: ./repository

    - id: create-dbcontext
      name: Criar DbContext
      action: roadiehq:utils:fs:write
      input:
        path: ./repository/${{ parameters.projectName }}/Data/${{ parameters.dbContextName }}.cs
        content: |
          using Microsoft.EntityFrameworkCore;

          namespace Data
          {
              public class ${{ parameters.dbContextName }} : DbContext
              {
                  public ${{ parameters.dbContextName }}(DbContextOptions<${{ parameters.dbContextName }}> options)
                      : base(options)
                  {
                  }
              }
          }

    - id: register-dbcontext
      name: Registrar DbContext
      action: roadiehq:utils:fs:append
      input:
        path: ./repository/${{ parameters.projectName }}/Program.cs
        after:
          - "builder.Services"
        content: |
          builder.Services.AddDbContext<${{ parameters.dbContextName }}>(options =>
              options.UseSqlServer("Server=localhost;Database=app;User Id=sa;Password=Your_password123;"));
