apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-webapi
  title: Web API .NET
  description: Cria uma Web API .NET 8 com Docker
  tags:
    - dotnet
    - webapi
    - api

spec:
  owner: platform-team
  type: service

  parameters:
    - title: Informações do Serviço
      required:
        - componentId
        - description
      properties:
        componentId:
          title: Nome do serviço
          type: string
          description: Nome único do componente e repositório
        description:
          title: Descrição
          type: string

    - title: Repositório GitHub
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repositório
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Gerar código base
      action: fetch:template
      input:
        url: ./content
        values:
          componentId: ${{ parameters.componentId }}
          description: ${{ parameters.description }}

    - id: publish
      name: Criar repositório no GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main

    - id: register
      name: Registrar no catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repositório GitHub
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Abrir no Catálogo
        icon: catalog
        entityRef: component:${{ parameters.componentId }}
