apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ componentId }}
  description: {{ description }}
  tags:
    - dotnet
    - webapi
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
