apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-webapi
  title: Web API .NET
  description: Cria uma Web API .NET 8 com Docker
  tags:
    - dotnet
    - webapi
    - api
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Informações do serviço
      required:
        - name
      properties:
        name:
          title: Nome
          type: string
          description: Nome único do componente
          ui:autofocus: true

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: Serviço ${{ parameters.name }}
        repoUrl: github.com?owner=MDev-Debug&repo=${{ parameters.name }}
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - user:default/guest
        title: Template executado
        info: Seu template foi executado com sucesso
        severity: normal

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}