apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: web-api-template
  title: .NET Web API Template
  description: Cria uma Web API .NET básica com csproj e Program.cs
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Informações do Projeto
      required:
        - name
      properties:
        name:
          title: Nome do Projeto
          type: string
          description: O nome da sua Web API

  steps:
    - id: fetch-base
      name: Buscando Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publicar no GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'Nova Web API criada via Backstage'
        repoUrl: 'github.com?owner=meu-org&repo=${{ parameters.name }}'

    - id: register
      name: Registrar no Catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repositório
        url: ${{ steps['publish'].output.remoteUrl }}